AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SNS-related functions for chatGPT-POC

Resources:
  GenerateCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/courses/generate-course.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: src/handlers/courses
      Layers:
      - !Ref SharedLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Description: A function that generates a courses
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
          FIREBASE_STORAGE_BUCKET: easify-courses-images
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
          ENABLE_IMAGE_GEN: true
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref CourseTopic

  GenerateCourseImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/courses/add-images.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: src/handlers/courses
      Layers:
      - !Ref SharedLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 300
      Description: A function that generates images a list of courses
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
          FIREBASE_STORAGE_BUCKET: easify-routine-images
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref CourseImagesTopic

  GenerateCourseQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/courses/generate-course-queue.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: src/handlers/courses
      Layers:
      - !Ref SharedLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 300
      Description: A function that generates a list of courses
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref CourseTopic
      Role: !GetAtt GenerateCourseQueueFunctionRole.Arn
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref CourseQueueTopic

  GenerateCourseQueueFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GenerateCourseQueueFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - SNS:Publish # Allow publishing to SNS topics
                Resource: !Ref CourseTopic # Use Ref to dynamically reference the SNS topic ARN

  GenerateRecipesBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/recipes/batch-generate-recipe.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: src/handlers/recipes
      Layers:
      - !Ref SharedLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Description: A function that generates recipes with images
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
          FIREBASE_STORAGE_BUCKET: easify-recipe-images
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref BatchRecipeTopic

  GenerateCareersBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/growth/generate-careers.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: src/handlers/growth
      Layers:
      - !Ref SharedLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Description: A function that generates industry with jobs
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref BatchIndustryTopic

  PopulateIndustriesBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/growth/populate-industries.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: src/handlers/growth
      Layers:
      - !Ref SharedLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Description: A function that generates industry details
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref BatchIndustryPopulateTopic

  GenerateFinancialPlansBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/financial/generate-plans.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: src/handlers/financial
      Layers:
      - !Ref SharedLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Description: A function that generates financial plans
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref BatchFinancialPlanTopic

  GenerateWorkoutsBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/workouts/batch-generate-workout.lambdaHandler
      Runtime: nodejs18.x
      CodeUri: src/handlers/workouts
      Layers:
      - !Ref SharedLayer
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Description: A function that generates workouts
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
          FIREBASE_STORAGE_BUCKET: easify-routine-images
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
          ENABLE_IMAGE_GEN: true
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref BatchWorkoutTopic

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/handlers/shared
      CompatibleRuntimes:
        - nodejs18.x

  CourseQueueTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: chatGPT-CourseQueueSNSTopic

  CourseTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: chatGPT-CourseSNSTopic

  CourseImagesTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: chatGPT-CourseImagesSNSTopic

  BatchRecipeTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: chatGPT-RecipesSNSTopic

  BatchWorkoutTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: chatGPT-WorkoutsSNSTopic

  BatchIndustryTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: chatGPT-IndustrySNSTopic

  BatchIndustryPopulateTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: chatGPT-IndustryPopulateSNSTopic

  BatchFinancialPlanTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: BatchFinancialPlanSNSTopic

Outputs:
  CourseTopicArn:
    Description: ARN of the Course SNS Topic
    Value: !Ref CourseTopic

  CourseImagesTopicArn:
    Description: ARN of the Course Images SNS Topic
    Value: !Ref CourseImagesTopic

  BatchRecipeTopicArn:
    Description: ARN of the Batch Recipe SNS Topic
    Value: !Ref BatchRecipeTopic