AWSTemplateFormatVersion: 2010-09-09
Description: >-
  chatGPT-POC
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ChatGPTApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ChatGPTApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type,Authorization'"
        AllowOrigin: "'*'"

  GetChatGPTPromptFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/chat/get-chat-gpt-prompt.lambdaHandler
      CodeUri: src/handlers/chat
      Layers:
        - !Ref SharedLayer
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 300
      Description: A function that returns the response from the chat prompt
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ChatGPTApi
            Path: /getPrompt
            Method: POST

  GetEasifyAiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/chat/get-easify-ai.lambdaHandler
      CodeUri: src/handlers/chat
      Layers:
        - !Ref SharedLayer
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 300
      Description: A function that returns the easify response
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ChatGPTApi
            Path: /easifyAi
            Method: POST
            RequestParameters:
              - method.request.header.Authorization:true

  GenerateAvatarFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/user/generate-avatar.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 300
      Description: A function that generates an avatar
      Policies:
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/secrets.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-prompts/prompts.json
        - Version: 2012-10-17
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: arn:aws:s3:::easify-secrets/firebase-account.json
      Environment:
        Variables:
          SECRETS_S3_BUCKET_NAME: easify-secrets
          SECRETS_S3_KEY_NAME: secrets.json
          PROMPTS_S3_BUCKET_NAME: easify-prompts
          PROMPTS_S3_KEY_NAME: prompts.json
          FIREBASE_ACCOUNT_S3_KEY_NAME: firebase-account.json
          FIREBASE_STORAGE_BUCKET: easify-avatars
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ChatGPTApi
            Path: /generateAvatar
            Method: POST
            RequestParameters:
              - method.request.header.Authorization:true

  SendShoppingListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/shopping/send-shopping-list.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 300
      Description: A function that sends a shopping list as a text message
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - SNS:Publish
              Resource: "*" # This allows publishing to all phone numbers.
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ChatGPTApi
            Path: /sendShoppingList
            Method: POST

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/handlers/shared
      CompatibleRuntimes:
        - nodejs18.x

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

  WebSocketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./websocket-stack.yaml

  SNSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sns-stack.yaml

Outputs:
  SharedLayerExport:
    Description: ARN of the SharedLayer
    Value: !Ref SharedLayer
    Export:
      Name: !Sub "${AWS::StackName}-SharedLayer"

  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ChatGPTApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  WebSocketEndpoint:
    Value: !GetAtt WebSocketStack.Outputs.WebSocketEndpoint
    Description: WebSocket API Endpoint
